#!/bin/bash

function setup_mariadb() {
    apt install -y mariadb-server python-pymysql
    cd /etc/mysql
    find . -name "*.cnf" | xargs -i sed -i "s,utf8mb4,utf8,g" {}
    conf_file="/etc/mysql/mariadb.conf.d/99-openstack.cnf"

    cat <<"EOF">$conf_file
[mysqld]
bind-address = 0.0.0.0

default-storage-engine = innodb
innodb_file_per_table
max_connections = 4096
collation-server = utf8_general_ci
character-set-server = utf8
EOF
    sed -i "s,127.0.0.1,0.0.0.0,g" /etc/mysql/my.cnf
    service mysql restart
}
