#!/bin/bash

function setup_ntp() {
    apt install -y chrony
    conf_file="/etc/chrony/chrony.conf"
cat <<"EOF">$conf_file
keyfile /etc/chrony/chrony.keys
commandkey 1
driftfile /var/lib/chrony/chrony.drift
log tracking measurements statistics
logdir /var/log/chrony
maxupdateskew 100.0
dumponexit
dumpdir /var/lib/chrony
local stratum 10
allow 10/8
allow 192.168/16
allow 172.16/12
allow 10.0.3.0/24
logchange 0.5
rtconutc
EOF

    conf_key="/etc/chrony/chrony.keys"
    echo "1 YOB0kNkh" > $conf_key
    service chrony restart
}
